# Shark_vs_dragons

## 1 Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2 Import and Merge databases

In [2]:
shark_ent = pd.read_csv("~/Desktop/Shark_vs_dragons/shark_tank_companies.csv")

In [3]:
shark_ent.head()

,deal,description,episode,category,entrepreneurs,location,website,askedfor,exchangeforstake,valuation,season,shark1,shark2,shark3,shark4,shark5,title,episode_season,multiple_entreprenuers
0,False,Bluetooth device implant for your ear.,1,Novelties,Darrin Johnson,"St. Paul, MN",NaN,1000000,15,6666667,1,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Ionic Ear,1-1,False
1,True,Retail and wholesale pie factory with two reta...,1,Specialty Food,Tod Wilson,"Somerset, NJ",http://whybake.com/,460000,10,4600000,1,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Mr. Tod's Pie Factory,1-1,False
2,True,Ava the Elephant is a godsend for frazzled par...,1,Baby and Child Care,Tiffany Krumins,"Atlanta, GA",http://www.avatheelephant.com/,50000,15,333333,1,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Ava the Elephant,1-1,False
3,False,"Organizing, packing, and moving services deliv...",1,Consumer Services,"Nick Friedman, Omar Soliman","Tampa, FL",http://collegehunkshaulingjunk.com/,250000,25,1000000,1,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,College Foxes Packing Boxes,1-1,False
4,False,Interactive media centers for healthcare waiti...,1,Consumer Services,Kevin Flannery,"Cary, NC",http://www.wispots.com/,1200000,10,12000000,1,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Wispots,1-1,False

In [4]:
shark_inv = pd.read_csv("~/Desktop/Shark_vs_dragons/shark_tank_deals.csv")

In [5]:
shark_inv.head()

,Season_Epi_code,Pitched_Business_Identifier,Pitched_Business_Desc,Deal_Status,Deal_Shark
0,826,Bridal Buddy,a functional slip worn under a wedding gown th...,1,KOL+LG
1,826,Laid Brand,hair-care products made with pheromones . Laid...,0,NaN
2,826,Rocketbook,a notebook that can scan contents to cloud ser...,0,NaN
3,826,Wine & Design,painting classes with wine served . Wine & Des...,1,KOL
4,824,Peoples Design,a mixing bowl with a built-in scoop . Peoples ...,1,LG

In [6]:
shark_inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season_Epi_code              706 non-null    int64
 1   Pitched_Business_Identifier  706 non-null    object
 2   Pitched_Business_Desc        706 non-null    object
 3   Deal_Status                  706 non-null    int64
 4   Deal_Shark                   383 non-null    object
dtypes: int64(2), object(3)
memory usage: 27.7+ KB

In [7]:
shark_inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season_Epi_code              706 non-null    int64
 1   Pitched_Business_Identifier  706 non-null    object
 2   Pitched_Business_Desc        706 non-null    object
 3   Deal_Status                  706 non-null    int64
 4   Deal_Shark                   383 non-null    object
dtypes: int64(2), object(3)
memory usage: 27.7+ KB

In [8]:
shark_ent_copy = shark_ent.copy()

In [9]:
shark_inv_copy = shark_inv.copy()

In [10]:
#Merge dfs with a left join (keeping shark_ent as a base)
shark_merged = pd.merge(shark_inv, shark_ent, left_on = "Pitched_Business_Identifier",  right_on = "title", how="left")

In [11]:
shark_merged

,Season_Epi_code,Pitched_Business_Identifier,Pitched_Business_Desc,Deal_Status,Deal_Shark,deal,description,episode,category,entrepreneurs,...,valuation,season,shark1,shark2,shark3,shark4,shark5,title,episode_season,multiple_entreprenuers
0,826,Bridal Buddy,a functional slip worn under a wedding gown th...,1,KOL+LG,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,826,Laid Brand,hair-care products made with pheromones . Laid...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,826,Rocketbook,a notebook that can scan contents to cloud ser...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,826,Wine & Design,painting classes with wine served . Wine & Des...,1,KOL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,824,Peoples Design,a mixing bowl with a built-in scoop . Peoples ...,1,LG,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,101,Ava the Elephant,"(Emmy the Elephant during show, trademarked a...",1,BC,True,Ava the Elephant is a godsend for frazzled par...,1.0,Baby and Child Care,Tiffany Krumins,...,333333.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Ava the Elephant,1-1,False
706,101,College Foxes Packing Boxes,a packing and organizing service based on an a...,0,NaN,False,"Organizing, packing, and moving services deliv...",1.0,Consumer Services,"Nick Friedman, Omar Soliman",...,1000000.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,College Foxes Packing Boxes,1-1,False
707,101,Ionic Ear,an implantable Bluetooth device requiring surg...,0,NaN,False,Bluetooth device implant for your ear.,1.0,Novelties,Darrin Johnson,...,6666667.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Ionic Ear,1-1,False
708,101,Mr. Tod's Pie Factory,a pie company,1,BC+DJ,True,Retail and wholesale pie factory with two reta...,1.0,Specialty Food,Tod Wilson,...,4600000.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Mr. Tod's Pie Factory,1-1,False
709,101,Wispots,an electronic hand-held device for waiting roo...,0,NaN,False,Interactive media centers for healthcare waiti...,1.0,Consumer Services,Kevin Flannery,...,12000000.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Wispots,1-1,False

In [12]:
shark_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 710 entries, 0 to 709
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season_Epi_code              710 non-null    int64
 1   Pitched_Business_Identifier  710 non-null    object
 2   Pitched_Business_Desc        710 non-null    object
 3   Deal_Status                  710 non-null    int64
 4   Deal_Shark                   385 non-null    object
 5   deal                         395 non-null    object
 6   description                  395 non-null    object
 7   episode                      395 non-null    float64
 8   category                     395 non-null    object
 9   entrepreneurs                342 non-null    object
 10  location                     395 non-null    object
 11  website                      363 non-null    object
 12  askedfor                     395 non-null    float64
 13  exchangeforstake             395 non-null    float64
 14  valuation                    395 non-null    float64
 15  season                       395 non-null    float64
 16  shark1                       395 non-null    object
 17  shark2                       395 non-null    object
 18  shark3                       395 non-null    object
 19  shark4                       395 non-null    object
 20  shark5                       395 non-null    object
 21  title                        395 non-null    object
 22  episode_season               395 non-null    object
 23  multiple_entreprenuers       395 non-null    object
dtypes: float64(5), int64(2), object(17)
memory usage: 138.7+ KB

In [13]:
shark_merged_copy = shark_merged.copy()

## 3 Data Wrangling

### 3.1 Dealing with missing values

Missing values and percentages are identified.

In [14]:
shark_merged.isna().sum().sort_values(ascending = False)

entrepreneurs                  368
website                        347
Deal_Shark                     325
askedfor                       315
deal                           315
description                    315
episode                        315
category                       315
location                       315
episode_season                 315
multiple_entreprenuers         315
exchangeforstake               315
valuation                      315
season                         315
shark1                         315
shark2                         315
shark3                         315
shark4                         315
shark5                         315
title                          315
Deal_Status                      0
Pitched_Business_Desc            0
Pitched_Business_Identifier      0
Season_Epi_code                  0
dtype: int64

In [15]:
missing_values = shark_merged_copy.isna().sum().sort_values(ascending = False)

In [16]:
len(shark_merged_copy)

710

In [17]:
percentage_missing_values = round(missing_values/len(shark_merged_copy),2)
percentage_missing_values

entrepreneurs                  0.52
website                        0.49
Deal_Shark                     0.46
askedfor                       0.44
deal                           0.44
description                    0.44
episode                        0.44
category                       0.44
location                       0.44
episode_season                 0.44
multiple_entreprenuers         0.44
exchangeforstake               0.44
valuation                      0.44
season                         0.44
shark1                         0.44
shark2                         0.44
shark3                         0.44
shark4                         0.44
shark5                         0.44
title                          0.44
Deal_Status                    0.00
Pitched_Business_Desc          0.00
Pitched_Business_Identifier    0.00
Season_Epi_code                0.00
dtype: float64

Missing values in the column "entrepreneurs" and related columns are analyzed.

In [18]:
shark_merged_copy[shark_merged_copy["entrepreneurs"].isna()]["season"].value_counts()

5.0    42
6.0    10
4.0     1
Name: season, dtype: int64

In [19]:
shark_merged_copy["season"].value_counts()

6.0    97
5.0    83
4.0    81
1.0    54
3.0    47
2.0    33
Name: season, dtype: int64

Seasons and episodes are analyzed. The first digit refers to the season and the rest refers to the episode. Season 7 and 8 are only present in one dataset. Hence the data is deleted.

In [20]:
print(sorted(set(shark_merged_copy["Season_Epi_code"])))

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 201, 202, 203, 204, 205, 206, 207, 208, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 822, 823, 824, 826]

In [21]:
shark_merged_copy.loc[shark_merged_copy["Season_Epi_code"] >= 701]

,Season_Epi_code,Pitched_Business_Identifier,Pitched_Business_Desc,Deal_Status,Deal_Shark,deal,description,episode,category,entrepreneurs,...,valuation,season,shark1,shark2,shark3,shark4,shark5,title,episode_season,multiple_entreprenuers
0,826,Bridal Buddy,a functional slip worn under a wedding gown th...,1,KOL+LG,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,826,Laid Brand,hair-care products made with pheromones . Laid...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,826,Rocketbook,a notebook that can scan contents to cloud ser...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,826,Wine & Design,painting classes with wine served . Wine & Des...,1,KOL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,824,Peoples Design,a mixing bowl with a built-in scoop . Peoples ...,1,LG,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,702,Splikity,password manager software that can sync across...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,701,Acton,motorized roller skates that strap onto shoes ...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,701,McClary Bros. Drinking Vinegars,a line of vinegars to be used in cocktails and...,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,701,SignalVault,a protector for credit cards to prevent them f...,1,LG+RH,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,701,The Beebo,a baby bottle holder to make feeding easier . ...,1,LG,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
shark_merged_copy.drop(shark_merged_copy.loc[shark_merged_copy["Season_Epi_code"] >= 701].index, inplace = True)

In [23]:
print(sorted(set(shark_merged_copy["Season_Epi_code"])))

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 201, 202, 203, 204, 205, 206, 207, 208, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629]

In [24]:
shark_merged_copy.isna().sum()

Season_Epi_code                  0
Pitched_Business_Identifier      0
Pitched_Business_Desc            0
Deal_Status                      0
Deal_Shark                     242
deal                           103
description                    103
episode                        103
category                       103
entrepreneurs                  156
location                       103
website                        135
askedfor                       103
exchangeforstake               103
valuation                      103
season                         103
shark1                         103
shark2                         103
shark3                         103
shark4                         103
shark5                         103
title                          103
episode_season                 103
multiple_entreprenuers         103
dtype: int64

## Change column names

Column names are changed for better readability.

In [25]:
#Make everything lowercase
shark_merged_copy.columns.str.lower()

Index(['season_epi_code', 'pitched_business_identifier',
       'pitched_business_desc', 'deal_status', 'deal_shark', 'deal',
       'description', 'episode', 'category', 'entrepreneurs', 'location',
       'website', 'askedfor', 'exchangeforstake', 'valuation', 'season',
       'shark1', 'shark2', 'shark3', 'shark4', 'shark5', 'title',
       'episode_season', 'multiple_entreprenuers'],
      dtype='object')

In [26]:
#Insert underscores and correct typos
shark_merged_copy.columns = ['season_epi_code', 'pitched_business_identifier', 'pitched_business_desc', 'deal_status', 'deal_shark', 'deal',
       'description', 'episode', 'category', 'entrepreneurs', 'location', 'website', 'asked_for', 'exchange_for_stake', 'valuation', 'season',
       'shark1', 'shark2', 'shark3', 'shark4', 'shark5', 'title','episode_season', 'multiple_entrepreneurs']

In [27]:
shark_merged_copy

,season_epi_code,pitched_business_identifier,pitched_business_desc,deal_status,deal_shark,deal,description,episode,category,entrepreneurs,...,valuation,season,shark1,shark2,shark3,shark4,shark5,title,episode_season,multiple_entrepreneurs
212,629,Bee Thinking,beehives in various modern designs . Matt Reed...,0,NaN,False,Bee Thinking crafts beautiful bee hives in Por...,24.0,Professional Services,Matt Reed,...,4000000.0,6.0,Lori Greiner,Robert Herjavec,Kevin O'Leary,Daymond John,Mark Cuban,Bee Thinking,6-24,False
213,629,Budsies,a company that creates custom plush toys based...,0,NaN,False,Budsies magically transforms any artwork into ...,24.0,Toys and Games,Alex Furmansky,...,2000000.0,6.0,Lori Greiner,Robert Herjavec,Kevin O'Leary,Daymond John,Mark Cuban,Budsies,6-24,False
214,629,Forus Athletics,workout and athletic shoes,0,NaN,False,Lightweight yet supportive and extremely comfo...,24.0,Men and Women's Shoes,Joel Vinocur and Arsene Millogo,...,1333333.0,6.0,Lori Greiner,Robert Herjavec,Kevin O'Leary,Daymond John,Mark Cuban,Forus Athletics,6-24,True
215,629,PullyPalz,a pulley system to keep two pacifiers availabl...,1,LG,True,A baby toy that helps them retrieve dropped pa...,24.0,Baby and Child Care,Julie Thompson,...,500000.0,6.0,Lori Greiner,Robert Herjavec,Kevin O'Leary,Daymond John,Mark Cuban,PullyPalz,6-24,False
216,628,BeeSweet Lemonade,honey-sweetened lemonade with flaxseed,1,DJ,True,BeeSweet Lemonade uses locally sourced honey. ...,23.0,Non-Alcoholic Beverages,Mikaila and Theo Ulmer,...,600000.0,6.0,Lori Greiner,Robert Herjavec,Kevin O'Leary,Daymond John,Mark Cuban,BeeSweet Lemonade,6-23,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,101,Ava the Elephant,"(Emmy the Elephant during show, trademarked a...",1,BC,True,Ava the Elephant is a godsend for frazzled par...,1.0,Baby and Child Care,Tiffany Krumins,...,333333.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Ava the Elephant,1-1,False
706,101,College Foxes Packing Boxes,a packing and organizing service based on an a...,0,NaN,False,"Organizing, packing, and moving services deliv...",1.0,Consumer Services,"Nick Friedman, Omar Soliman",...,1000000.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,College Foxes Packing Boxes,1-1,False
707,101,Ionic Ear,an implantable Bluetooth device requiring surg...,0,NaN,False,Bluetooth device implant for your ear.,1.0,Novelties,Darrin Johnson,...,6666667.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Ionic Ear,1-1,False
708,101,Mr. Tod's Pie Factory,a pie company,1,BC+DJ,True,Retail and wholesale pie factory with two reta...,1.0,Specialty Food,Tod Wilson,...,4600000.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Mr. Tod's Pie Factory,1-1,False
709,101,Wispots,an electronic hand-held device for waiting roo...,0,NaN,False,Interactive media centers for healthcare waiti...,1.0,Consumer Services,Kevin Flannery,...,12000000.0,1.0,Barbara Corcoran,Robert Herjavec,Kevin O'Leary,Daymond John,Kevin Harrington,Wispots,1-1,False

In [28]:
sharks = shark_merged_copy.to_csv('shark_merged_copy.csv', index=False)